language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra-google-m2repository
  - extra-android-m2repository
script:
- "./gradlew assembleDebug"
deploy:
  provider: releases
  api_key:
    secure: zQBRvHJnIZiQmKuuMxgmc441Iub+5WsRyRGJAYctE/djwXt7Ug8UBs6RMTV2rIR3kwfKz9oucC/uVJRYVEnpRqFvkImW9L2uSgQL6Cbzjjkj6K/GgKDnLf7UgdG90HVfxV2Ip3+cMR1/ZqyrzND7AJxVdd1ycYRMjAoyTcXihAzbLCSCapYA0dt3cLtxDXfCbSAuGxNFLjJm8d8zpE3T7f4pLzOC2L2tIZVmMtH/vVxgJaPsyFdQZkjoatqLCh2/134wpl4Wcvm37xzeN5JW3Tl9b5iiQse4mFKGD8o1fHUDePkqY2DZVQph3ddOZMjCbAvLBNpjQ2yYboZNv26tSwd6pmSv6n7mfdWZobnk6ZgV9WdhXMivNkfBGSnRGJDp+Z/uUiWoH9d+VvMMOX7vv5MrXe1/z+BK80XkW7Bf7BvklA8Zwv38+Y/GPfyHb1ImMey0Bx8zlhYiy6eMPRPUl2IdfhZQ7rH6P5VC4oRKs+9hhajePVFMPP+TkunFdIviqRYuQOgMVVZFlA1JqyZvIMTGMAppLe5+DR0vMFYPCWgwsytRLbRRLGV87psf3Ip0RqKwjlscA9T2Bb/iNJe6QJdsTKSYXrWBYrN/ckXU517vVaQuUCj5MTpyKHxZ8K2yPB7pAKfhocoH3AvdKaNHVlcSRlo9kPW4f0gFqrjrZ3c=
  file: app/build/outputs/apk/app-debug.apk
  skip_cleanup: true
  on:
    repo: adamiltone/iem-qcode-4-11-2016
    tags: true